title: Aathil Ducky Notes
description: >-
  My personal markdown-powered notes and knowledge base.
baseurl: ""  # Keep this empty since you're using a user/organization site
url: "https://aathilducky.github.io"

theme: minima
  # or replace with another Jekyll theme like minimal-mistakes

# Optional - navigation links
header_pages:
  - index.md
  - about.md

# Build settings
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-seo-tag


remote_theme: aathilducky/jekyll-ducky-notes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag


# Exclude these from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Enable future posts (optional)
future: true

# Optional social metadata
author:
  name: Aathil Ducky
  email: aathilducky@email.com
